apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    targetRevision: 0.25.0
    helm:
      valueFiles:
        - values.yaml
    chart: vault
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
