apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-jobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: helm-commands-container
        image: alpine:latest
        command: ["/bin/sh"]
        args:
        - -c
        - |
          helm repo add hashicorp https://helm.releases.hashicorp.com
          helm install vault hashicorp/vault --set "server.dev.enabled=true"
      restartPolicy: Always
