apiVersion: batch/v1
kind: Job
metadata:
  name: helm-commands-job
spec:
  template:
    spec:
      containers:
      - name: helm-commands-container
        image: alpine:latest
        command: ["/bin/sh"]
        args:
        - -c
        - |
          helm repo add hashicorp https://helm.releases.hashicorp.com
          helm install vault hashicorp/vault --set "server.dev.enabled=true"
      restartPolicy: Never
  backoffLimit: 4
